=== Acrónimos

.Acrónimos
|===
|Acrónimo |Descripción |Notas

|TDD
|Test Driven Development
|¡BIEN! https://en.wikipedia.org/wiki/Test-driven_developmentp[Wikipedia]

|BDD
|Behavioural Driven Development
|¡BIEN! https://en.wikipedia.org/wiki/Behavior-driven_development[Wikipedia]

|CVDD
|CV Driven Development
|¡MAL!
|===

=== Recursos

TIP: Las contribuciones son bienvenidas...lee más en cómo https://github.com/eddiejaoude/book-open-source-tips/blob/master/.github/CONTRIBUTING.md[contribuir]

[quote, Contribuir al Código Abierto en GitHub, https://guides.github.com/activities/contributing-to-open-source/]
Una gran manera de involucrarse en el código abierto es contribuir a los proyectos existentes que estás usando. GitHub alberga más de 5 millones de proyectos de código abierto. Hay proyectos para cada conjunto de habilidades como recetas, HTML/CSS, Ruby, Astrofísica y muchas más. Esta guía cubrirá lo que podrías encontrar en un proyecto típico y cómo hacer una buena contribución.

[quote, La Guía del Principiante para Contribuir a los Proyectos de Código Abierto, https://blog.newrelic.com/2014/05/05/open-source_gettingstarted/]
El código abierto funciona teniendo bastante gente contribuyendo a la creación y mantenimiento del software. La cosa es, funciona bien sólo cuando las personas están contribuyendo de verdad. Los proyectos de código abierto exitosos prosperan con una amplia variedad de contribuciones de personas con todos los niveles de habilidades de codificación y compromiso. Si sólo una persona repara un aviso de compilador, elimina un bug, o añade a la documentación, muy pronto estarás hablando de un progreso real. Para muchas personas, la parte más difícil es iniciarse. Así que aquí están algunas formas sugeridas para comenzar a contribuir de inmediato, en el nivel que sea más cómodo para ti.

[quote, Cómo contribuir a un proyecto de código abierto en GitHub, http://blog.davidecoppola.com/2016/11/howto-contribute-to-open-source-project-on-github/]
GitHub es hogar de muchos proyectos populares de código abierto como Ruby en Rails, jQuery, Docker, Go y muchos más. La forma en la que las personas (usualmente) contribuyen a un proyecto de código abierto en GitHub es usando pull requests. Un pull request es básicamente un parche que incluye más información y que le permite a los miembros discutirlo en el sitio web.

[quote, Un viaje muy accidentado de principiantes a través del mundo del código abierto, https://medium.freecodecamp.com/a-beginners-very-bumpy-journey-through-the-world-of-open-source-4d108d540b39#.an82epenf]
Está bien saberlo todo, y tomar un paso a la vez al momento de aprender algo nuevo. No pierdas demasiado tiempo eligiendo el proyecto “correcto”. Si conoces un proyecto o una organización con una comunidad amigable con los principiantes, empieza ahí. Un enorme agradecimiento a todos los encargados de mantenimiento de código abierto que han sido súper receptivos y que alienten a los nuevos contribuidores. Está ayudando a los recién llegados a navegar por enormes bases de código y a contribuir de una manera pequeña pero significativa. Tus esfuerzos son realmente apreciados y necesarios.

[quote, Cómo cuidar a la comunidad a través del código, https://opensource.com/article/16/12/community-over-code]
Quieres concentrarte en los elementos básicos para tu comunidad antes de profundizar en el código. "Lo haremos bien luego" no siempre funciona. Si no tomas decisiones de gobernanza ahora, las cosas pueden desmoronarse, o si tomas la desición equivocada, podrías perder a potenciales miembros de la comunidad en el futuro.

[quote, Lista de Verificación de Accesibilidad Web, http://a11yproject.com/checklist.html]
Para muchos desarrolladores web, la accesibilidad es compleja y de cierto modo difícil. El Proyecto de Accesibilidad entiende esto y queremos ayudar a hacer la accesibilidad web más fácil de implementar para desarrolladores de interfaz de usuario. Los ciegos y visualmente dispacitados conforman 285,000,000 de personas, de acuerdo a la Organización Mundial de la Salud (Junio 2012) con 39,000,000 categorizados como legalmente ciegos, y los restantes 246,000,000 como visualmente dispacitados. Sordos y discapacitados auditivos conforman 275,000,000 de personas (2004) en la categoría de discapacidad auditiva de moderada a profunda.
