=== Acronyms

.Acronyms
|===
|Acronym |Description |Notes

|TDD
|Test Driven Development
|GOOD! https://en.wikipedia.org/wiki/Test-driven_developmentp[Wikipedia]

|BDD
|Behavioural Driven Development
|GOOD! https://en.wikipedia.org/wiki/Behavior-driven_development[Wikipedia]

|CVDD
|CV Driven Development
|BAD!
|===

=== Resources

TIP: Suggestions welcome

[quote, Contributing to Open Source on GitHub, https://guides.github.com/activities/contributing-to-open-source/]
A great way to get involved in open source is to contribute to the existing projects you’re using. GitHub is home to more than 5 million open source projects. There are projects for every skill set like recipes, HTML/CSS, Ruby, Astrophysics and many more. This guide will cover what you might find in a typical project and how to make a great contribution.

[quote, The Beginner’s Guide to Contributing to Open Source Projects, https://blog.newrelic.com/2014/05/05/open-source_gettingstarted/]
Open source works by having many people contribute to the creation and maintenance of software. Thing is, it works well only when people are actually contributing. Successful open source projects thrive on a wide variety of contributions from people with all levels of coding skills and commitment. If just one person fixes a compiler warning, closes a bug, or adds to the documentation, pretty soon you’re talking real progress. For many people, the hardest part is just getting started. So here are some suggested ways you can begin contributing right away, at whatever level is most comfortable for you.

[quote, How to contribute to an open source project on GitHub, http://blog.davidecoppola.com/2016/11/howto-contribute-to-open-source-project-on-github/]
GitHub is the home of many popular open source projects like Ruby on Rails, jQuery, Docker, Go and many others. The way people (usually) contribute to an open source project on GitHub is using pull requests. A pull request is basically a patch which includes more information and allows members to discuss it on the website.
