=== Readme file

Documentation is usually left to last. At least have a `README.md` with some basic information, for example QuickStart.

=== Contribution file

One of the main benefits of an Open Source project & its community is Contributions. Lower the barrier to entry with a `CONTRUBTION.md` file in the root of your Open Source project. Read more about https://github.com/blog/1184-contributing-guidelines[GitHub Contribution file]

=== Code of Conduct

Your community needs to feel safe, diverse & included. Make sure you have a Code of Conduct for your project & community. Read more about https://github.com/blog/2039-adopting-the-open-code-of-conduct[Open Code of Conducts]

=== GitHub template files

Issue & Pull Request templates really help keeping the project consistent & reminds people not to leave out certain useful information.

=== Commits

Commits should contain a single item, then your commit message will be easier to write & describe what you have done. There are many benefits to this:

* Looking back through the history will be clear & easy to understand
 - if you want to find something
 - undo / remove some work
* Automate the changelog generation as part of your build for tag & package etc

=== Little & often

Steady projects not only look more stable, but are generally more successful & are better for your health. Trying doing a little every week.

=== Plan ahead

Create or check tasks today ready for tomorrow. Two benefits of this, allowing you tomorrow to immediately hit the ground running & to digest the tasks overnight as you might make some final tweaks.

=== Respond to Issues & Pull Requests

Always respond to Issues & Pull Requests in a timely fashion, ideally 48hours (even if it is with a comment of, I will take a look next week).

=== Pull Requests

If you spent the time doing the work, make sure you add a description to your your Pull Request to make it easier for the Review to review your work. Raise an Issue first so a plan of action can be discussed before you begin the work.

=== Reviews

Even if it is only you on the project, try to raise Pull Requests & get a friend to review it. This is so valuable.

=== Automated tests & Continuous Integration

Automate everything! This helps lower the barrier to entry & increase repeatability.

* Automated tests have many benefits & give confidence in the state & quality of the application:
 - Unit tests are great for design & architecture of functionality
 - Integration tests are great for the touch points
 - End-to-end tests are great for full appliaction testing & simulate the user
* Run the automated tests on Continuous Integration (CI) (for example http://travis-ci.org[TravisCI])
* When autonated tests are successful, deploy the application aka Continuous Delivery (CD)

Note: This include database schema migrations etc
