include::do/do-readme.adoc[]

include::do/do-code-block.adoc[]

include::do/do-contribution-file.adoc[]

include::do/do-code-of-conduct.adoc[]

include::do/do-github-template-files.adoc[]

include::do/do-licensing.adoc[]

include::do/do-git-commit.adoc[]

include::do/do-little-and-often.adoc[]

include::do/do-plan-ahead.adoc[]

include::do/do-issue-task.adoc[]

include::do/do-always-respond.adoc[]

include::do/do-pull-request.adoc[]

include::do/do-review.adoc[]

include::do/do-automation.adoc[]

include::do/do-prototyping.adoc[]

include::do/do-optimal-time.adoc[]

=== Never enough time

We all have the same 24 hours in a day available to us. It's what you do with it that counts. Try to find a small amount of time per day, even 10 minutes when you are on the toilet - yes you heard me right "on the toilet". Multi tasking in that situation is possible, but trying to work while watching TV is very unproductive.

=== Make it open source (public) from day 1

I do NOT understand people who say "I will make it public when it is finished". First of all, it will never be finished, secondly you then do not gain all the benefits from Open Source.

=== Leave the codebase better than you found it

Many code repositories (mostly Closed Source ones) go from bad to worse. Open Source projects tend to do the complete opposite due to it being in the public eye. Even the smallest of improvements add up and really help - no improvement is too small.
