include::do/do-readme.adoc[]

include::do/do-code-block.adoc[]

include::do/do-contribution-file.adoc[]

include::do/do-code-of-conduct.adoc[]

include::do/do-github-template-files.adoc[]

include::do/do-licensing.adoc[]

include::do/do-git-commit.adoc[]

include::do/do-little-and-often.adoc[]

include::do/do-plan-ahead.adoc[]

include::do/do-issue-task.adoc[]

include::do/do-always-respond.adoc[]

=== Pull Requests

If you spent the time doing the work, make sure you add a description to your your Pull Request to make it easier for the reviewer to digest your work. Raise an Issue first so a plan of action can be discussed before you begin the work and to remind yourself of the goals set out in that task.

=== Reviews

Even if it is only you on the project, try to raise Pull Requests & get a friend to review it. This approach is invaluable as a second pair of eyes often picks up oversights.

=== Automated tests & Continuous Integration

Automate everything! This helps lower the barrier to entry & increase repeatability.

* Automated tests have many benefits & give confidence in the state & quality of the application:
 - Unit tests are great for design & architecture of functionality
 - Integration tests are great for the touch points
 - End-to-end tests are great for full appliaction testing & simulate the user
* Run the automated tests on Continuous Integration (CI) (for example http://travis-ci.org[TravisCI])
* When automated tests are successful, deploy the application aka Continuous Delivery (CD)

Note: This includes database schema migrations, asset building and anything that is required by the end product

=== Get a Prototype to your users quickly

Get feedback as soon as possible. Quick and dirty prototypes in front of some of your users will give you instant feedback and direction. Remember to make it clear it is a prototype.

=== Work at your optimal time

People work better at different times of the day and night so find your most efficient and optimal time. Even if that is 11pm at night or 4am, try utilise your most productive time.

=== Never enough time

We all have the same 24 hours in a day available to us. It's what you do with it that counts. Try to find a small amount of time per day, even 10 minutes when you are on the toilet - yes you heard me right "on the toilet". Multi tasking in that situation is possible, but trying to work while watching TV is very unproductive.

=== Make it open source (public) from day 1

I do NOT understand people who say "I will make it public when it is finished". First of all, it will never be finished, secondly you then do not gain all the benefits from Open Source.

=== Leave the codebase better than you found it

Many code repositories (mostly Closed Source ones) go from bad to worse. Open Source projects tend to do the complete opposite due to it being in the public eye. Even the smallest of improvements add up and really help - no improvement is too small.
