=== Readme file

Documentation is usually left to last. At least have a `README.md` with some basic information, for example QuickStart.

=== Contribution file

One of the main benefits of an Open Source project & its community is Contributions. Lower the barrier to entry with a `CONTRUBTION.md` file in the root of your Open Source project. Read more about https://github.com/blog/1184-contributing-guidelines[GitHub Contribution file]

=== Code of Conduct

Your community needs to feel safe, diverse & included. Make sure you have a Code of Conduct for your project & community. Read more about https://github.com/blog/2039-adopting-the-open-code-of-conduct[Open Code of Conducts]

=== GitHub template files

Issue & Pull Request templates really help keeping the project consistent & reminds people not to leave out certain useful information.

=== Commits

Commits should contain a single item, then your commit message will be easier to write & describe what you have done. There are many benefits to this:

* Looking back through the history will be clear & easy to understand
 - if you want to find something
 - undo / remove some work
* Automate the changelog generation as part of your build for tag & package etc

=== Little & often

Steady projects not only look more stable, but are generally more successful & are better for your health. Trying doing a little every week.
