= Open Source Tips
By Eddie Jaoude
:toc:

:author:   Eddie Jaoude
:twitter:  https://twitter.com/eddiejaoude
:date:     2016
:version:  0.1.0
:repo:     https://github.com/eddiejaoude/book-open-source-tips
:docinfo1:

[abstract]
== Abstract

This book is a collection of DO & DONT tips for Open Source software.

[preface]
== Preface

Open Source is really dominating the industry, with so many projects out there from well known organisations like Facebook, Twitter and NetFlix; to passionate individuals around the world. How do you share your work and how do you decide who's work to use with so much choice available.

As with technology that keep on changing, this book will need continually updating, suggestions, tweaks and pull requests are welcome. Currently on version v{version}.

Source Repository is on GitHub {repo}

<<<
== Introduction

With so many popular Open Source projects & many people contributing to Open Source, it would be beneficial to capture the pros & cons. Open Source not only benefits the community but also the authors as they get feedback on their project from a technical and lower level, more exposure and marketing, testing and bug fixing etc.

TIP: This book will continually be updated, please check the version {version}. Any question please contact the author {author} on {twitter}.

<<<
== DO's

Recommended...

include::do.adoc[]

<<<
== DONT's

NOT recommended...

include::dont.adoc[]
