= Mga Paaalalahanan sa Open Source
By Eddie Jaoude
:toc:

:author:    Eddie Jaoude
:twitter:   https://twitter.com/eddiejaoude
:date:      2016
:version:   0.1.0
:repo:      https://github.com/eddiejaoude/book-open-source-tips
:imagesdir: images
:docinfo1:

[abstract]
== Buod

Ang aklat na ito ay naglalaman ng mga karaniwang DAPAT at HINDI DAPAT GAWIN para sa Open Source na software.

[preface]
== Paunang Salita

Ang komunidad ng Open Source ay patuloy na lumalago. Sa bawat araw na dumarami ang bilang ng mga proyektong Open Source, gayundin ang hukbo ng mga nag-aambag para panatilihin sila. Bagaman nakakapanabik ito para sa industriya, maaari itong maging katakot-takot para sa isang bagong tagabuo sa komunidad. Ang aklat na ito ay naglalayon na magbigay ng iilang mga paaalalahanan para sa mga baguhan upang makatulong sa kanila na iwasan ang mga patibong sa pagbuo ng Open Source at para matuto mula sa pangkalahatang kaalaman ng komunidad.

Ika nga sa lumang kawikaan, "_Ang oras at ang alon [at teknolohiya] ay hindi naghihintay sa sinumang tao_". At sa abot ng aming makakaya, maging ang aklat ding ito. Tandaang tingnan ang bilang ng bersyon para sa mga update! Kami’y kasalukuyang nasa v{version}.

Lubos naming ikagagalak ang inyong tulong upang mapanatiling naka-update ang aklat na ito. Ang inyong mga komento, suhestiyon at pull requests ay malugod naming tinatanggap. Maaari niyong hanapin ang repository sa Github: {repo}.

Kung may iba pa kayong mga katanungan, mangyari lamang na makipag-ugnay sa may-akda na si {author} sa {twitter}.

<<<
== Panimula

Nangingibabaw ang Open Source sa industriya ng software. Ang mga kampeon nito'y pinabibilangan ng mga tanyag na organisasyon tulad ng Facebook, Twitter, Netflix, LinkedIn at Google (Android/Chrome), ngunit ang mas mahalaga, ang hukbo ng mga dedikadong indibidwal na tagabuo sa buong mundo. Ang kanilang mga pagsisikap ay nagkaroon ng epekto sa halos bawat bahagi ng computer science, nagresulta sa milyun-milyong open source na proyekto na may bilyun-bilyong mga linya ng code!

Habang ang masaganang ecosystem na ito ay nagbigay ng malaking tulong sa buong industriya, maaari rin itong magpahirap sa mga baguhan na hindi alam kung saan magsisimula. Kung ikaw ay isang baguhan, maaari mong harapin ang mga katanungang _"Paano ako makakaambag sa komunidad ng Open Source?"_ O, _"Paano ako pipili sa pagitan ng napakaraming nakikipagkompetensiyang proyekto?"_. Ang mga sumusunod na mga DAPAT at HINDI DAPAT GAWIN ay naglalayon na masagot ang mga katanungang iyon, pati na rin ang ibang mga payo para sa nagbabalak na maging tagabuo ng Open Source.

Tara na't sisirin natin ito.

PAALALA: Ang mga proyektong hindi isinapubliko sa simula ay may mas mataas na pagkakataong ipagkatiwala ang mga pribadong kredensyal sa kasaysayan, kung kaya't mas nirerekomendang gawing pampubliko ang mga proyekto sa simula pa lang. Ang pagsasaad na sila ay hindi pa tapos ay hindi isang dahilan, dahil kailanman, sila ay hindi matatapos. Kung isinapubliko sa simula pa lamang, pinaparating lang noon na ang tamang pananaw ang ginamit kaya naman mababawasan ang panganib.


<<<
== Mga Dapat Gawin

include::do.adoc[]

<<<
== Mga Hindi Dapat Gawin

include::dont.adoc[]

<<<
== Apendiks

include::appendix.adoc[]
