= Open Source Tips
By Eddie Jaoude
:toc:

:author:    Eddie Jaoude
:twitter:   https://twitter.com/eddiejaoude
:date:      2016
:version:   0.1.0
:repo:      https://github.com/eddiejaoude/book-open-source-tips
:imagesdir: images
:docinfo1:

[abstract]
== Abstract

This book contains some common DOs & DON'Ts for Open Source software.

[preface]
== Preface

The Open Source community is thriving. Each day the number of Open Source projects grows, as does the army of contributors that maintain them. While this is exciting for the industry, it can be daunting as a developer new to the community. This book aims to provide some tips for newcomers to help them avoid the pitfalls of Open Source development and learn from the community's collective wisdom.

As the ancient proverb goes, _Time and tide [and technology] wait for no man_. And to the best of our ability, neither will this book. Remember to check the version number for updates! We're currently on v{version}.

We would love your help in keeping this book updated. Your comments, suggestions and pull requests are most welcome. You can find the repository on GitHub: {repo}.

If you have any questions, please contact the author, {author} on {twitter}.

<<<
== Introduction

Open Source is dominating the software industry. Its champions include well known organisations like Facebook, Twitter and Netflix, but more significantly, an army of passionate individual developers around the world. Their efforts have impacted almost every part of computer science, culminating in millions of open source projects, with billions of lines of code! There are several websites that can help you make your project open source, using git. GitHub is by far the most popular one and what this project is based in, but others include GitLab, which is perhaps equally as powerful; most of these services use git so if for some reason you need to switch hosts, there isn't a big learning curve.

While this abundant ecosystem has been of huge benefit to the whole industry, it can also make it difficult for newcomers to know where to start. If you're a newcomer, you might be faced with questions such as _"How can I contribute to the Open Source community?"_ Or, _"How do I choose between so many competing projects?"_. The following DOs and DON'Ts aim to address some of those basic questions, plus some pointers for aspiring Open Source developers.

Let's dive right in.

<<<
== DOs

include::do.adoc[]

<<<
== DON'Ts

include::dont.adoc[]
