=== Automation - Tests, Continuous Integration (CI), Continuous Deployment (CD)

*Automate everything*! This helps lower the barrier to entry & increase repeatability.

* Automated tests have many benefits & give confidence in the state & quality of the application:
 - Unit tests are great for design & architecture of functionality
 - Integration tests are great for the touch points
 - End-to-end tests are great for full application testing & simulate the user
* It should be very easy to setup up a local environment & run all these tests
* Run the automated tests on Continuous Integration (CI) after someone has pushed their code changes to a feature branch
* When automated tests are successful, deploy the application aka Continuous Delivery (CD)

NOTE: This includes database schema migrations, asset building and anything that is required by the end product

TIP: http://travis-ci.org[TravisCI] is highly recommended in Open Source projects. Very easy to set up & get going, all from a simple YAML file.
