=== Git de commit

Los Git de commits deberían ser pequeños y atómicos, sin importar si son un solo cambio o un rasgo menor. Esto hará que tus mensajes de confirmación de cambios sean más fáciles de escribir y que los cambios estén agrupados de forma lógica. Esto trae consigo muchos beneficios:

* Revisar el historial será claro y sencillo de comprender
 - si quieres encontrar algo
 - deshacer / remover algún trabajo
* Automatizar la generación del changelog como parte de tu construcción para etiquetas y paquetes, entre otros

==== Mensaje de Commit

* Reduce el asunto a `50` caracteres
* No termines el asunto con un punto `.`.
* Si más de `50` caracteres usan el cuerpo (descripción)
* Cierra el cuerpo al llegar a los `72` caracteres.
* Usa el cuerpo para explicar el `porqué` y no el `cómo`, esto se puede ver en el código

Para más información http://chris.beams.io/posts/git-commit/[Git Commit]

TIP: Antes de hacer el commit, revisa el `git diff` para asegurarte de que no estás haciendo definitivo un cambio indeseado o que no debería hacerse.
