=== Archivos de plantillas de GitHub 

Las plantillas de Issues y Pull Requests son realmente útiles para mantener la consistencia del proyecto y les recuerda a las personas que no deber dejar por fuera cierta información importante.

[quote, GitHub, Plantilla de Issue de GitHub ]
Para agregar una plantilla de Issue a un repositorio, crea un archivo llamado ISSUE_TEMPLATE en el directorio raíz. Una extensión del archivo es opcional, pero los archivos Markdown files (.md) son compatibles. La compatibilidad con Markdown hace que sea más sencillo añadir cosas como encabezados, links, @-menciones, y listas de tareas a tus planillas.

[quote, GitHub, Plantilla de Pull Request de GitHub]
Las plantillas de Pull Request siguen el mismo modelo: añade un archivo llamado PULL_REQUEST_TEMPLATE al directorio raíz de tu repositorio.

[quote, GitHub, Directorio Oculto de GitHub para Plantillas]
Si te preocupa el desorden añadido en el directorio raíz de tu proyecto, también añadimos compatibilidad para una carpeta .github/. Puedes poner archivos CONTRIBUTING.md, ISSUE_TEMPLATE.md, y PULL_REQUEST_TEMPLATE.md en .github/ y todo funcionará tal y como se espera.

https://help.github.com/articles/helping-people-contribute-to-your-project/[Todos los detalles provistos por GitHub] para ayudar a las personas a contribuir con tu proyecto.
