=== Licenciar

No es requerido seleccionar una licencia. Sin embargo, al hacerlo, estás seleccionando "No License" la cual te pondrá por defecto en el https://help.github.com/articles/github-terms-of-service/[T&Cs] de GitHub. GitHub ha creado una buena página web informativa para ayudarte a elegir una http://choosealicense.com[licencia]

Ejemplos abajo desde http://choosealicense.com["Choose an open source license"]:

[quote, Elige una licencia, Licencia MIT]
La Licencia MIT es una licencia permitiva que es corta y directa. Le permite a las personas hacer lo que quieran con tu código siempre y cuando te devuelvan atribución y no te haga responsable.

NOTA: jQuery, .NET Core, y Rails usan la Licencia MIT.

[quote, Elige una Licencia, Licencia Apache 2.0]
La Licencia Apache 2.0 es una licencia permisiva parecida a la Licencia MIT, pero también provee una concesión expresa de los derechos de patente de los contribuyentes a los usuarios.

NOTA: Android, Apache, y Swift usan la Licencia Apache 2.0.

[quote, Elige una Licencia, GNU GPLv3]
La GNU GPLv3 es una licencia copyleft que requiere que cualquiera que contribuya a tu código o a un trabajo derivado haga que la fuente esté disponible bajo los mismo términos, y también proporciona una concesión expresa de derechos de patente de los contribuyentes a los usuarios.

NOTA: Bash, GIMP, y Privacy Badger usan la GNU GPLv3.

[quote, Elige una Licencia, No License]
Cuando haces un trabajo creativo (lo que incluye código), el trabajo está bajo copyright exclusivo por defecto. A menos que incluyas una licencia que especifique otra cosa, nadie más puede usar, copiar, distribuir, o modificar tu trabajo sin riesgo de caídas, sacudidas, o litigio. Una vez que el trabajo tenga otros contribuyentes (siendo cada uno titular de derechos de autor), “nadie” empieza, incluyéndote.

CUIDADO: Como un consumidor, si encuentras software que no tiene una licencia, eso significa que no tienes permiso de los creadores del software para usar, modificar, o compartir el software. Aunque un host de código como GitHub puede permitirle ver y bifurcar el código, esto no implica que tienes permiso de usar, modificar, o compartir el software para cualquier propósito. Tus opciones son: Pedirle a los encargados de mantenimiento de manera agradable que añadan una licencia. No uses el software. Negocia una licencia privada con un abogado.
