=== Pull Requests

Si inviertes el tiempo haciendo el trabajo, asegúrate de que añadiste un descripción a tu Pull Request para hacer que sea más fácil para el revisor digerir tu trabajo. Sube un Asunto primero, así puede ser discutido un plan de acción antes de que empieces el trabajo y para recordarte a ti mismo los objetivos propuestos para el cometido.

Los Pull Requests deberían ser enlazados al Asunto original que está tratando de solucionar. Esto puede hacerse usando `#` seguido de *Issue No*, e.g. `#123`. La descripción del Asunto contendrá la información previa, por lo que la descripción del Pull Request debería contener la información posterior a los cambios. Incluye material visual también, diagramas y capturas de pantalla, por ejemplo.

Recuerda, mantenlo corto. Por ejemplo, si tus cambios contienen una característica o una solución a un bug y cambios al estilo de código, deberían estar en Pull Requests separados. Lo ideal es que cada proyecto tenga 10 Pull Requests, en lugar de 1 o 2 Pull Requests masivos.

TIP: Los Pull Request deberían ser un solo cambio o característica.

Multiples commits en un Pull Request resaltan los pasos de creación del Pull Request. No intentes hacer todo en un solo commit.

Los comentarios importan, si hay alguna duda, ponla ahí, es más fácil removerlas que añadirlas. No describas cómo, eso está en el código obviamente, describe por qué.
